import React from 'react';
import { useWorkspaceStore } from '../../../app/store/useWorkspaceStore';
import { useLabStore } from '../../../app/store/useLabStore';
import { useSimulationStore } from '../../../app/store/useSimulationStore';
import { useTimelineStore } from '../../../app/store/useTimelineStore';
import { Network, Server, Share2, Activity, ShieldAlert, CheckCircle2 } from 'lucide-react';
import { CURRICULUM } from '../../../data/curriculum';

const CATEGORIES = [
  { id: 'Foundations', label: 'Foundations', icon: Network, color: 'text-blue-500', bg: 'bg-blue-500/10' },
  { id: 'Addressing', label: 'Addressing', icon: Activity, color: 'text-purple-500', bg: 'bg-purple-500/10' },
  { id: 'Transport', label: 'Transport', icon: Share2, color: 'text-indigo-500', bg: 'bg-indigo-500/10' },
  { id: 'Services', label: 'Services', icon: Server, color: 'text-amber-500', bg: 'bg-amber-500/10' },
  { id: 'Switching', label: 'Switching', icon: Share2, color: 'text-indigo-500', bg: 'bg-indigo-500/10' },
  { id: 'Routing', label: 'Routing', icon: Activity, color: 'text-emerald-500', bg: 'bg-emerald-500/10' },
  { id: 'Troubleshooting', label: 'Troubleshooting', icon: ShieldAlert, color: 'text-rose-500', bg: 'bg-rose-500/10' }
];

export const LabsView: React.FC = () => {
  const setTab = useWorkspaceStore(state => state.setTab);
  const startLab = useLabStore(state => state.startLab);
  const progress = useLabStore(state => state.progress);
  const resetEngine = useSimulationStore(state => state.reset);
  const engine = useSimulationStore(state => state.engine);

  const handleStartLab = (labId: string) => {
    resetEngine();
    
    // Clear out the basic lab devices generated by reset()
    engine.clear();
    
    const labDef = CURRICULUM.find(l => l.id === labId);
    if (labDef && labDef.initialState) {
      labDef.initialState.devices.forEach(d => engine.addDevice(d));
      labDef.initialState.links.forEach(l => engine.addLink(l));
    }
    
    // Sync store
    useSimulationStore.setState({
      devices: engine.getDevices(),
      links: engine.getLinks()
    });

    startLab(labId);
      useTimelineStore.getState().setReplayMode(false, engine.createSnapshot());
    setTab('sandbox');
  };

  const activeCategories = CATEGORIES.filter(cat => CURRICULUM.some(l => l.category === cat.id));

  return (
    <div className="w-full h-full flex flex-col overflow-y-auto bg-base text-primary pb-20 pt-8 px-4 md:px-8">
      <header className="mb-6">
        <h1 className="text-3xl font-black tracking-tight mb-2">Curriculum</h1>
        <p className="text-secondary">Master networking through guided interactive labs.</p>
      </header>

      <div className="flex flex-col gap-6 max-w-4xl w-full mx-auto pb-10">
        {activeCategories.map(cat => {
          const Icon = cat.icon;
          const catLabs = CURRICULUM.filter(l => l.category === cat.id);
          
          return (
            <section key={cat.id} className="mb-4">
              <div className="flex items-center gap-3 mb-4">
                <div className={`p-2 rounded-lg ${cat.bg} ${cat.color}`}>
                  <Icon className="w-5 h-5" />
                </div>
                <h2 className="text-xl font-bold">{cat.label}</h2>
              </div>
              
              <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                {catLabs.map(lab => {
                  const prog = progress[lab.id];
                  const isCompleted = prog?.status === 'Completed';

                  return (
                    <div 
                      key={lab.id}
                      onClick={() => handleStartLab(lab.id)}
                      className="bg-surface border border-border rounded-xl p-5 hover:border-accent cursor-pointer transition-all active:scale-[0.98] shadow-sm hover:shadow-md relative overflow-hidden"
                    >
                      <div className="flex justify-between items-start mb-2">
                        <span className={`text-[10px] font-bold px-2 py-0.5 rounded uppercase tracking-wide ${lab.difficulty === 'Beginner' ? 'bg-success/20 text-success' : lab.difficulty === 'Intermediate' ? 'bg-accent/20 text-accent' : 'bg-danger/20 text-danger'}`}>
                          {lab.difficulty}
                        </span>
                        {isCompleted && (
                          <span className="flex items-center gap-1 text-[10px] font-bold text-success bg-success/10 px-2 py-0.5 rounded uppercase tracking-wide">
                            <CheckCircle2 className="w-3 h-3" /> Completed
                          </span>
                        )}
                        {!isCompleted && prog?.status === 'In Progress' && (
                          <span className="flex items-center gap-1 text-[10px] font-bold text-accent bg-accent/10 px-2 py-0.5 rounded uppercase tracking-wide">
                            In Progress
                          </span>
                        )}
                      </div>
                      <h3 className="font-bold text-lg mb-1 pr-4">{lab.title}</h3>
                      <p className="text-sm font-medium text-secondary mb-3">{lab.subtitle}</p>
                      <p className="text-sm text-muted line-clamp-2 mb-4">{lab.description}</p>
                      <div className="flex items-center justify-between mt-auto pt-3 border-t border-border/50">
                        <span className="text-xs text-muted font-medium">{lab.estimatedTime} mins</span>
                        <span className="text-xs font-bold text-accent group-hover:underline">Launch Lab &rarr;</span>
                      </div>
                    </div>
                  );
                })}
              </div>
            </section>
          );
        })}
      </div>
    </div>
  );
};
